{
  "formatVersion": "1.1",
  "component": {
    "group": "com.squareup.sqldelight",
    "module": "core",
    "version": "1.5.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "xwktddyadzbtnf4duirkvykzdi"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.alecstrong",
          "module": "sqlite-psi-core",
          "version": {
            "requires": "0.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-1.5.0-SNAPSHOT.jar",
          "url": "core-1.5.0-SNAPSHOT.jar",
          "size": 416851,
          "sha512": "d447d5efccb4eca9e76a0d05f6e7dd1503d42649877a427582b329f45b7c7c18773edacb8e1a353cebacc173e255bdcec3b445aa382b7ba6475aefbc5eec8bb2",
          "sha256": "fce899e55000e633ba3956f0d0642446e8d194f2185845b19d689ba5f3642a24",
          "sha1": "211de55229ecf95e1257a44743bd104728a433d8",
          "md5": "f3dcde680532c586aa0fb674b80b6044"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.7.2"
          }
        },
        {
          "group": "org.xerial",
          "module": "sqlite-jdbc",
          "version": {
            "requires": "3.34.0"
          }
        },
        {
          "group": "com.alecstrong",
          "module": "sqlite-psi-core",
          "version": {
            "requires": "0.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-1.5.0-SNAPSHOT.jar",
          "url": "core-1.5.0-SNAPSHOT.jar",
          "size": 416851,
          "sha512": "d447d5efccb4eca9e76a0d05f6e7dd1503d42649877a427582b329f45b7c7c18773edacb8e1a353cebacc173e255bdcec3b445aa382b7ba6475aefbc5eec8bb2",
          "sha256": "fce899e55000e633ba3956f0d0642446e8d194f2185845b19d689ba5f3642a24",
          "sha1": "211de55229ecf95e1257a44743bd104728a433d8",
          "md5": "f3dcde680532c586aa0fb674b80b6044"
        }
      ]
    }
  ]
}
