{
  "formatVersion": "1.1",
  "component": {
    "group": "com.squareup.sqldelight",
    "module": "coroutines-extensions",
    "version": "1.5.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "xwktddyadzbtnf4duirkvykzdi"
    }
  },
  "variants": [
    {
      "name": "iosArm32-api",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coroutines-extensions-iosarm32/1.5.0-SNAPSHOT/coroutines-extensions-iosarm32-1.5.0-SNAPSHOT.module",
        "group": "com.squareup.sqldelight",
        "module": "coroutines-extensions-iosarm32",
        "version": "1.5.0-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64-api",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coroutines-extensions-iosarm64/1.5.0-SNAPSHOT/coroutines-extensions-iosarm64-1.5.0-SNAPSHOT.module",
        "group": "com.squareup.sqldelight",
        "module": "coroutines-extensions-iosarm64",
        "version": "1.5.0-SNAPSHOT"
      }
    },
    {
      "name": "iosX64-api",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coroutines-extensions-iosx64/1.5.0-SNAPSHOT/coroutines-extensions-iosx64-1.5.0-SNAPSHOT.module",
        "group": "com.squareup.sqldelight",
        "module": "coroutines-extensions-iosx64",
        "version": "1.5.0-SNAPSHOT"
      }
    },
    {
      "name": "jsLegacy-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../coroutines-extensions-js/1.5.0-SNAPSHOT/coroutines-extensions-js-1.5.0-SNAPSHOT.module",
        "group": "com.squareup.sqldelight",
        "module": "coroutines-extensions-js",
        "version": "1.5.0-SNAPSHOT"
      }
    },
    {
      "name": "jsLegacy-runtime",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../coroutines-extensions-js/1.5.0-SNAPSHOT/coroutines-extensions-js-1.5.0-SNAPSHOT.module",
        "group": "com.squareup.sqldelight",
        "module": "coroutines-extensions-js",
        "version": "1.5.0-SNAPSHOT"
      }
    },
    {
      "name": "jsIr-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../coroutines-extensions-js/1.5.0-SNAPSHOT/coroutines-extensions-js-1.5.0-SNAPSHOT.module",
        "group": "com.squareup.sqldelight",
        "module": "coroutines-extensions-js",
        "version": "1.5.0-SNAPSHOT"
      }
    },
    {
      "name": "jsIr-runtime",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../coroutines-extensions-js/1.5.0-SNAPSHOT/coroutines-extensions-js-1.5.0-SNAPSHOT.module",
        "group": "com.squareup.sqldelight",
        "module": "coroutines-extensions-js",
        "version": "1.5.0-SNAPSHOT"
      }
    },
    {
      "name": "jvm-api",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../coroutines-extensions-jvm/1.5.0-SNAPSHOT/coroutines-extensions-jvm-1.5.0-SNAPSHOT.module",
        "group": "com.squareup.sqldelight",
        "module": "coroutines-extensions-jvm",
        "version": "1.5.0-SNAPSHOT"
      }
    },
    {
      "name": "jvm-runtime",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../coroutines-extensions-jvm/1.5.0-SNAPSHOT/coroutines-extensions-jvm-1.5.0-SNAPSHOT.module",
        "group": "com.squareup.sqldelight",
        "module": "coroutines-extensions-jvm",
        "version": "1.5.0-SNAPSHOT"
      }
    },
    {
      "name": "macosX64-api",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coroutines-extensions-macosx64/1.5.0-SNAPSHOT/coroutines-extensions-macosx64-1.5.0-SNAPSHOT.module",
        "group": "com.squareup.sqldelight",
        "module": "coroutines-extensions-macosx64",
        "version": "1.5.0-SNAPSHOT"
      }
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../coroutines-extensions-metadata/1.5.0-SNAPSHOT/coroutines-extensions-metadata-1.5.0-SNAPSHOT.module",
        "group": "com.squareup.sqldelight",
        "module": "coroutines-extensions-metadata",
        "version": "1.5.0-SNAPSHOT"
      }
    },
    {
      "name": "tvosArm64-api",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coroutines-extensions-tvosarm64/1.5.0-SNAPSHOT/coroutines-extensions-tvosarm64-1.5.0-SNAPSHOT.module",
        "group": "com.squareup.sqldelight",
        "module": "coroutines-extensions-tvosarm64",
        "version": "1.5.0-SNAPSHOT"
      }
    },
    {
      "name": "tvosX64-api",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coroutines-extensions-tvosx64/1.5.0-SNAPSHOT/coroutines-extensions-tvosx64-1.5.0-SNAPSHOT.module",
        "group": "com.squareup.sqldelight",
        "module": "coroutines-extensions-tvosx64",
        "version": "1.5.0-SNAPSHOT"
      }
    },
    {
      "name": "watchosArm32-api",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coroutines-extensions-watchosarm32/1.5.0-SNAPSHOT/coroutines-extensions-watchosarm32-1.5.0-SNAPSHOT.module",
        "group": "com.squareup.sqldelight",
        "module": "coroutines-extensions-watchosarm32",
        "version": "1.5.0-SNAPSHOT"
      }
    },
    {
      "name": "watchosArm64-api",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coroutines-extensions-watchosarm64/1.5.0-SNAPSHOT/coroutines-extensions-watchosarm64-1.5.0-SNAPSHOT.module",
        "group": "com.squareup.sqldelight",
        "module": "coroutines-extensions-watchosarm64",
        "version": "1.5.0-SNAPSHOT"
      }
    },
    {
      "name": "watchosX86-api",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coroutines-extensions-watchosx86/1.5.0-SNAPSHOT/coroutines-extensions-watchosx86-1.5.0-SNAPSHOT.module",
        "group": "com.squareup.sqldelight",
        "module": "coroutines-extensions-watchosx86",
        "version": "1.5.0-SNAPSHOT"
      }
    }
  ]
}
