{
  "formatVersion": "1.1",
  "component": {
    "url": "../../native-driver/1.5.0-SNAPSHOT/native-driver-1.5.0-SNAPSHOT.module",
    "group": "com.squareup.sqldelight",
    "module": "native-driver",
    "version": "1.5.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "xwktddyadzbtnf4duirkvykzdi"
    }
  },
  "variants": [
    {
      "name": "tvosX64-api",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.squareup.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "1.5.0-SNAPSHOT"
          }
        },
        {
          "group": "co.touchlab",
          "module": "sqliter",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-common",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-concurrency",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-collections",
          "version": {
            "requires": "1.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "native-driver.klib",
          "url": "native-driver-tvosx64-1.5.0-SNAPSHOT.klib",
          "size": 36180,
          "sha512": "12fc778272ecabd0bc85d5c80e729f0871c60514c3e0169874074c8736d40001c7091cb7e6ee9863c3a4cb5385c07ddbd4d614ea685b3b1c753cdc9b3d7e4323",
          "sha256": "1a51931fc16f68ac77adb8ad564acd7134178193c4f6a053fd35c4d700447a0b",
          "sha1": "a0524cc2a41f1435eb29c485b8b519aa5643bdfa",
          "md5": "c3263316c9d8dea03c251caca06af49c"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../native-driver-metadata/1.5.0-SNAPSHOT/native-driver-metadata-1.5.0-SNAPSHOT.module",
        "group": "com.squareup.sqldelight",
        "module": "native-driver-metadata",
        "version": "1.5.0-SNAPSHOT"
      }
    }
  ]
}
