{
  "formatVersion": "1.1",
  "component": {
    "group": "com.squareup.sqldelight",
    "module": "sqlite-driver",
    "version": "1.5.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "xwktddyadzbtnf4duirkvykzdi"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup.sqldelight",
          "module": "jdbc-driver",
          "version": {
            "requires": "1.5.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "sqlite-driver-1.5.0-SNAPSHOT.jar",
          "url": "sqlite-driver-1.5.0-SNAPSHOT.jar",
          "size": 5287,
          "sha512": "df0acb701f8f4cac57ed0a6b9de33049a17d6bae8bef824eaeb382beb664c6857be323de80dffb375f41377601d11e56ae1d7c064897fee0090000921c5357d6",
          "sha256": "1e6e465923ae0bfe24513cd75b60104464e10bd9dfe7f79bc37d1067a2fa9163",
          "sha1": "a08abbf21bd9d857486228624bb1a849e7ee832c",
          "md5": "9944a96676cc451dfdcee931d9c4d9cc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.xerial",
          "module": "sqlite-jdbc",
          "version": {
            "requires": "3.34.0"
          }
        },
        {
          "group": "com.squareup.sqldelight",
          "module": "jdbc-driver",
          "version": {
            "requires": "1.5.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "sqlite-driver-1.5.0-SNAPSHOT.jar",
          "url": "sqlite-driver-1.5.0-SNAPSHOT.jar",
          "size": 5287,
          "sha512": "df0acb701f8f4cac57ed0a6b9de33049a17d6bae8bef824eaeb382beb664c6857be323de80dffb375f41377601d11e56ae1d7c064897fee0090000921c5357d6",
          "sha256": "1e6e465923ae0bfe24513cd75b60104464e10bd9dfe7f79bc37d1067a2fa9163",
          "sha1": "a08abbf21bd9d857486228624bb1a849e7ee832c",
          "md5": "9944a96676cc451dfdcee931d9c4d9cc"
        }
      ]
    }
  ]
}
