{
  "formatVersion": "1.1",
  "component": {
    "group": "com.squareup.sqldelight",
    "module": "rxjava3-extensions",
    "version": "1.5.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "xwktddyadzbtnf4duirkvykzdi"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "rxjava3-extensions-1.5.0-SNAPSHOT.jar",
          "url": "rxjava3-extensions-1.5.0-SNAPSHOT.jar",
          "size": 11108,
          "sha512": "664125616b26c4852a98c339a6ebb47566fe325afb88b4a2263a31f2427fa4a7ae93204a61abd85b480f5904eaa9fb072007c607520e630f65f0e5cc59d5d7da",
          "sha256": "570beb647f54385a9098fc993f45621ea34cd7448bd1372be4e7bceeaf9337ba",
          "sha1": "c6362961d49441f628c1194c0c5e7db2b69f49f5",
          "md5": "8f1c8c3fabbdc320fcff957d7c8aed26"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "1.5.0-SNAPSHOT"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "rxjava3-extensions-1.5.0-SNAPSHOT.jar",
          "url": "rxjava3-extensions-1.5.0-SNAPSHOT.jar",
          "size": 11108,
          "sha512": "664125616b26c4852a98c339a6ebb47566fe325afb88b4a2263a31f2427fa4a7ae93204a61abd85b480f5904eaa9fb072007c607520e630f65f0e5cc59d5d7da",
          "sha256": "570beb647f54385a9098fc993f45621ea34cd7448bd1372be4e7bceeaf9337ba",
          "sha1": "c6362961d49441f628c1194c0c5e7db2b69f49f5",
          "md5": "8f1c8c3fabbdc320fcff957d7c8aed26"
        }
      ]
    }
  ]
}
