{
  "formatVersion": "1.1",
  "component": {
    "url": "../../native-driver-watchosx86/1.5.0-SNAPSHOT/native-driver-watchosx86-1.5.0-SNAPSHOT.module",
    "group": "com.squareup.sqldelight",
    "module": "native-driver-watchosx86",
    "version": "1.5.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "xwktddyadzbtnf4duirkvykzdi"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "com.squareup.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "1.5.0-SNAPSHOT"
          }
        },
        {
          "group": "co.touchlab",
          "module": "sqliter",
          "version": {
            "requires": "0.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "native-driver-metadata-1.5.0-SNAPSHOT.jar",
          "url": "native-driver-metadata-1.5.0-SNAPSHOT.jar",
          "size": 10248,
          "sha512": "aedc56015b0c01c55949d6ea00b5f31726a090db11d862f5ca53e1b1919021b216dfb83a1532608b10b8c7de4bc44a20608a4ab5b66ad992e1848780e26a8c3d",
          "sha256": "fc2fd143b20e34487eec2ead1496c7373af235e26ec8f9f3f4a4c597b87e25ff",
          "sha1": "b5d9b0ed1f1e995d282c35c08a624a4e01fadb03",
          "md5": "e45d7bf277b1df3cada42420a345b1a3"
        }
      ]
    }
  ]
}
