{
  "formatVersion": "1.1",
  "component": {
    "url": "../../native-driver/1.5.0-SNAPSHOT/native-driver-1.5.0-SNAPSHOT.module",
    "group": "com.squareup.sqldelight",
    "module": "native-driver",
    "version": "1.5.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "xwktddyadzbtnf4duirkvykzdi"
    }
  },
  "variants": [
    {
      "name": "watchosArm64-api",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.squareup.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "1.5.0-SNAPSHOT"
          }
        },
        {
          "group": "co.touchlab",
          "module": "sqliter",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-common",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-concurrency",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-collections",
          "version": {
            "requires": "1.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "native-driver.klib",
          "url": "native-driver-watchosarm64-1.5.0-SNAPSHOT.klib",
          "size": 36223,
          "sha512": "031c1e253d66518b6db98b0383bec64d61e48a2c28f8ea34ca4cd48b9ff416ab94017713b69f0b0874853ef9baddfe95a75057c164fbe097d0f02d005a5622d1",
          "sha256": "41edcf9afc26fd15678326d2fc3c3e600ee6f4ac7f4c7c78269f8eef7889e282",
          "sha1": "b01fb45cb38777ee0e4462a3fb566c1de9162490",
          "md5": "b8888ef74d4039526023eca0a500c5ff"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../native-driver-metadata/1.5.0-SNAPSHOT/native-driver-metadata-1.5.0-SNAPSHOT.module",
        "group": "com.squareup.sqldelight",
        "module": "native-driver-metadata",
        "version": "1.5.0-SNAPSHOT"
      }
    }
  ]
}
