{
  "formatVersion": "1.1",
  "component": {
    "group": "com.squareup.sqldelight",
    "module": "android-driver",
    "version": "1.5.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "3ehalzzixvearnsencjhgelklu"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.squareup.sqldelight",
          "module": "runtime-jvm",
          "version": {
            "requires": "1.5.0-SNAPSHOT"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "android-driver-1.5.0-SNAPSHOT.aar",
          "url": "android-driver-1.5.0-SNAPSHOT.aar",
          "size": 23088,
          "sha512": "aacd6c64f393960bb00dd9567cde5729224d787379703d4d0aa37e3d49f68c0dac89d0dfa38193ba47aaaa1df513bcf170248caba99101a10d03d4979061d4fd",
          "sha256": "c6ed6399e579cdd822d9c709c0b946a486bfda5019ddb45e065dedd8e418051a",
          "sha1": "73a5fed252736ca9b1876a5902b505df7abf6a1d",
          "md5": "d58ad68507b2d3345ab028341d0563c9"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.squareup.sqldelight",
          "module": "runtime-jvm",
          "version": {
            "requires": "1.5.0-SNAPSHOT"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-framework",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "android-driver-1.5.0-SNAPSHOT.aar",
          "url": "android-driver-1.5.0-SNAPSHOT.aar",
          "size": 23088,
          "sha512": "aacd6c64f393960bb00dd9567cde5729224d787379703d4d0aa37e3d49f68c0dac89d0dfa38193ba47aaaa1df513bcf170248caba99101a10d03d4979061d4fd",
          "sha256": "c6ed6399e579cdd822d9c709c0b946a486bfda5019ddb45e065dedd8e418051a",
          "sha1": "73a5fed252736ca9b1876a5902b505df7abf6a1d",
          "md5": "d58ad68507b2d3345ab028341d0563c9"
        }
      ]
    }
  ]
}
