{
  "formatVersion": "1.1",
  "component": {
    "url": "../../coroutines-extensions/1.5.0-SNAPSHOT/coroutines-extensions-1.5.0-SNAPSHOT.module",
    "group": "com.squareup.sqldelight",
    "module": "coroutines-extensions",
    "version": "1.5.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "xwktddyadzbtnf4duirkvykzdi"
    }
  },
  "variants": [
    {
      "name": "jvm-api",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.squareup.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "1.5.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "sqldelight-coroutines-extensions-jvm-1.5.0-SNAPSHOT.jar",
          "url": "coroutines-extensions-jvm-1.5.0-SNAPSHOT.jar",
          "size": 42380,
          "sha512": "1b6e3bc2b1d80907f2441d0fbe607a9c135a1c028823b7d86fbebeac431795b95dbacfa1d37820fc02a196bef360af89b5608b60fbd09b1081c746e40465398b",
          "sha256": "4c0d9ae8dce549e464e086f17dbbb718cb2913e4ea282aeffd4f0ee6a99187e9",
          "sha1": "2739f40a32f89baf69862f80fcc4cf8ff9b78414",
          "md5": "915278bc5873bca92bb837f5980c1c61"
        }
      ]
    },
    {
      "name": "jvm-runtime",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.squareup.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "1.5.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "sqldelight-coroutines-extensions-jvm-1.5.0-SNAPSHOT.jar",
          "url": "coroutines-extensions-jvm-1.5.0-SNAPSHOT.jar",
          "size": 42380,
          "sha512": "1b6e3bc2b1d80907f2441d0fbe607a9c135a1c028823b7d86fbebeac431795b95dbacfa1d37820fc02a196bef360af89b5608b60fbd09b1081c746e40465398b",
          "sha256": "4c0d9ae8dce549e464e086f17dbbb718cb2913e4ea282aeffd4f0ee6a99187e9",
          "sha1": "2739f40a32f89baf69862f80fcc4cf8ff9b78414",
          "md5": "915278bc5873bca92bb837f5980c1c61"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../coroutines-extensions-metadata/1.5.0-SNAPSHOT/coroutines-extensions-metadata-1.5.0-SNAPSHOT.module",
        "group": "com.squareup.sqldelight",
        "module": "coroutines-extensions-metadata",
        "version": "1.5.0-SNAPSHOT"
      }
    }
  ]
}
