{
  "formatVersion": "1.1",
  "component": {
    "url": "../../coroutines-extensions-watchosx86/1.5.0-SNAPSHOT/coroutines-extensions-watchosx86-1.5.0-SNAPSHOT.module",
    "group": "com.squareup.sqldelight",
    "module": "coroutines-extensions-watchosx86",
    "version": "1.5.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "3ehalzzixvearnsencjhgelklu"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "com.squareup.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "1.5.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "sqldelight-coroutines-extensions-metadata-1.5.0-SNAPSHOT.jar",
          "url": "coroutines-extensions-metadata-1.5.0-SNAPSHOT.jar",
          "size": 1781,
          "sha512": "23e5306e165f51baec64bc2b7db5834ecf29af4c50f68f518d3f0d95d9aa060c23af1c05f14e79ea95fdb6ccccfb6ccbc402069ba6f7c8d2c5c3c2f161bd19d4",
          "sha256": "cee9e9c8d0baa2cdff4850941b2a8f41ee7d49b5cc019794ff5c824d89b68637",
          "sha1": "66b41bbb6c0dec21c3790de07673e34ed0f88f3e",
          "md5": "fbe77477c44e9906cb735a767d4871cb"
        }
      ]
    }
  ]
}
