{
  "formatVersion": "1.1",
  "component": {
    "url": "../../native-driver/1.5.0-SNAPSHOT/native-driver-1.5.0-SNAPSHOT.module",
    "group": "com.squareup.sqldelight",
    "module": "native-driver",
    "version": "1.5.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "3ehalzzixvearnsencjhgelklu"
    }
  },
  "variants": [
    {
      "name": "iosArm64-api",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.squareup.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "1.5.0-SNAPSHOT"
          }
        },
        {
          "group": "co.touchlab",
          "module": "sqliter",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-common",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-concurrency",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-collections",
          "version": {
            "requires": "1.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "native-driver.klib",
          "url": "native-driver-iosarm64-1.5.0-SNAPSHOT.klib",
          "size": 36188,
          "sha512": "746b23f58746a6b66b81187da8401e9f8d12d7f44117d0559fb07774205d9ba0ee6c3f585c3ef856673116cd859316cda47e8c873c716aafade80c64b1318473",
          "sha256": "dadf5d7059b6fbdb281c746ed2417f5229c73adfce72854ad9e45699c0fd8357",
          "sha1": "35c0ff60b0ca01196578e739d69fa773cb591ff7",
          "md5": "0cf90d2aa2c28fd4eb445b291ce26777"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../native-driver-metadata/1.5.0-SNAPSHOT/native-driver-metadata-1.5.0-SNAPSHOT.module",
        "group": "com.squareup.sqldelight",
        "module": "native-driver-metadata",
        "version": "1.5.0-SNAPSHOT"
      }
    }
  ]
}
