{
  "formatVersion": "1.1",
  "component": {
    "url": "../../runtime/1.5.0-SNAPSHOT/runtime-1.5.0-SNAPSHOT.module",
    "group": "com.squareup.sqldelight",
    "module": "runtime",
    "version": "1.5.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "xwktddyadzbtnf4duirkvykzdi"
    }
  },
  "variants": [
    {
      "name": "macosX64-api",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-common",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-collections",
          "version": {
            "requires": "1.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "runtime.klib",
          "url": "runtime-macosx64-1.5.0-SNAPSHOT.klib",
          "size": 41303,
          "sha512": "40a00888b16568a84c06fc9d9a675b586b1faa2f780fb333eabb694f9a58620a69a80d24f99e58e563fad2e7d3d47e3fe3781ab4058515040efce6dd3876d6e8",
          "sha256": "4c328866cc1b53b990af5c2991c4d25e0def94f215e49ef2998c9f810ce304eb",
          "sha1": "0502a78747a2616b93dc36342eecbf1ec592460f",
          "md5": "e5cc8d6b43289347556623173147b0b5"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../runtime-metadata/1.5.0-SNAPSHOT/runtime-metadata-1.5.0-SNAPSHOT.module",
        "group": "com.squareup.sqldelight",
        "module": "runtime-metadata",
        "version": "1.5.0-SNAPSHOT"
      }
    }
  ]
}
