{
  "formatVersion": "1.1",
  "component": {
    "group": "com.squareup.sqldelight",
    "module": "migrations",
    "version": "1.5.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "xwktddyadzbtnf4duirkvykzdi"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.alecstrong",
          "module": "sqlite-psi-core",
          "version": {
            "requires": "0.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "migrations-1.5.0-SNAPSHOT.jar",
          "url": "migrations-1.5.0-SNAPSHOT.jar",
          "size": 14970,
          "sha512": "e619abb475c816338b2b498327db42f388d309171a2a9d9ce33c2644a1950b144871f37460bf537c8ab0fba13f9283fea009619bc63b4a0dcdab6ba9be8fdca6",
          "sha256": "9dbfcfadbd091b55e502c9f124a8581041aa6ec0e9cec1cbe62846a56abfa99d",
          "sha1": "147f9abfc051785f9cfafba582326e9d0710d170",
          "md5": "187287784d8b1d1a52cf749d98907c23"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.xerial",
          "module": "sqlite-jdbc",
          "version": {
            "requires": "3.34.0"
          }
        },
        {
          "group": "de.danielbechler",
          "module": "java-object-diff",
          "version": {
            "requires": "0.95"
          }
        },
        {
          "group": "us.fatehi",
          "module": "schemacrawler-tools",
          "version": {
            "requires": "14.16.04.01-java7"
          }
        },
        {
          "group": "us.fatehi",
          "module": "schemacrawler-sqlite",
          "version": {
            "requires": "14.16.04.01-java7"
          }
        },
        {
          "group": "com.alecstrong",
          "module": "sqlite-psi-core",
          "version": {
            "requires": "0.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "migrations-1.5.0-SNAPSHOT.jar",
          "url": "migrations-1.5.0-SNAPSHOT.jar",
          "size": 14970,
          "sha512": "e619abb475c816338b2b498327db42f388d309171a2a9d9ce33c2644a1950b144871f37460bf537c8ab0fba13f9283fea009619bc63b4a0dcdab6ba9be8fdca6",
          "sha256": "9dbfcfadbd091b55e502c9f124a8581041aa6ec0e9cec1cbe62846a56abfa99d",
          "sha1": "147f9abfc051785f9cfafba582326e9d0710d170",
          "md5": "187287784d8b1d1a52cf749d98907c23"
        }
      ]
    }
  ]
}
