{
  "formatVersion": "1.1",
  "component": {
    "url": "../../coroutines-extensions/1.5.0-SNAPSHOT/coroutines-extensions-1.5.0-SNAPSHOT.module",
    "group": "com.squareup.sqldelight",
    "module": "coroutines-extensions",
    "version": "1.5.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "xwktddyadzbtnf4duirkvykzdi"
    }
  },
  "variants": [
    {
      "name": "watchosX86-api",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.squareup.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "1.5.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.9-native-mt"
          }
        }
      ],
      "files": [
        {
          "name": "coroutines-extensions.klib",
          "url": "coroutines-extensions-watchosx86-1.5.0-SNAPSHOT.klib",
          "size": 10652,
          "sha512": "a74964209a0b042b487c7848cffb750419bd084b620ac403e47b3f64e5df269154941d577d0d5b1c5bc60125785ebb8e5745335c02508491eb49b7234a42f1ae",
          "sha256": "9b9950a7e8d3f02f6cdca4b5e4bb5dcf6aa1da3158117b5e9de2437b2acf6681",
          "sha1": "557da1ec2ee146b04613872b49c5921ef103b237",
          "md5": "bb40cda6dce1346dc718656931755bb4"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../coroutines-extensions-metadata/1.5.0-SNAPSHOT/coroutines-extensions-metadata-1.5.0-SNAPSHOT.module",
        "group": "com.squareup.sqldelight",
        "module": "coroutines-extensions-metadata",
        "version": "1.5.0-SNAPSHOT"
      }
    }
  ]
}
