{
  "formatVersion": "1.1",
  "component": {
    "group": "com.squareup.sqldelight",
    "module": "rxjava2-extensions",
    "version": "1.5.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "xwktddyadzbtnf4duirkvykzdi"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "rxjava2-extensions-1.5.0-SNAPSHOT.jar",
          "url": "rxjava2-extensions-1.5.0-SNAPSHOT.jar",
          "size": 11520,
          "sha512": "b2bcda30035f75a683e108a2f38af13ad81767fff55a33bf6a86d23185d1daf33472fdf4c8265ae6ff664ab28f23decc1b76a98aaebdb6478ab392fec05a2159",
          "sha256": "32f11dd97a6504ce75aa3e94fb47f5030130efe596e385171c70023a56bf21d8",
          "sha1": "b710803fb8853e24015b820d1b52c82ffd578cd6",
          "md5": "266790571f29fa87832d30dfdf43c2d7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "1.5.0-SNAPSHOT"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "rxjava2-extensions-1.5.0-SNAPSHOT.jar",
          "url": "rxjava2-extensions-1.5.0-SNAPSHOT.jar",
          "size": 11520,
          "sha512": "b2bcda30035f75a683e108a2f38af13ad81767fff55a33bf6a86d23185d1daf33472fdf4c8265ae6ff664ab28f23decc1b76a98aaebdb6478ab392fec05a2159",
          "sha256": "32f11dd97a6504ce75aa3e94fb47f5030130efe596e385171c70023a56bf21d8",
          "sha1": "b710803fb8853e24015b820d1b52c82ffd578cd6",
          "md5": "266790571f29fa87832d30dfdf43c2d7"
        }
      ]
    }
  ]
}
