{
  "formatVersion": "1.1",
  "component": {
    "url": "../../coroutines-extensions/1.5.0-SNAPSHOT/coroutines-extensions-1.5.0-SNAPSHOT.module",
    "group": "com.squareup.sqldelight",
    "module": "coroutines-extensions",
    "version": "1.5.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "3ehalzzixvearnsencjhgelklu"
    }
  },
  "variants": [
    {
      "name": "watchosArm32-api",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.squareup.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "1.5.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.9-native-mt"
          }
        }
      ],
      "files": [
        {
          "name": "coroutines-extensions.klib",
          "url": "coroutines-extensions-watchosarm32-1.5.0-SNAPSHOT.klib",
          "size": 10669,
          "sha512": "ada4c64f9a0e46c621aaf9ace449a2bb1ecccc967e33313e2a87eb81e09e36dc8005f859d93393b626983b72df841854544be1b6abb10d74aa5f5b83132b2d17",
          "sha256": "991946d451ce5f11171a1a77816a73179926177477cfb418fa0d1b440496ab0b",
          "sha1": "3a074e9dd876df357a2ce0a412ff9fde0f66ca10",
          "md5": "936aaba13f0996e366820bbc7a2b42c5"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../coroutines-extensions-metadata/1.5.0-SNAPSHOT/coroutines-extensions-metadata-1.5.0-SNAPSHOT.module",
        "group": "com.squareup.sqldelight",
        "module": "coroutines-extensions-metadata",
        "version": "1.5.0-SNAPSHOT"
      }
    }
  ]
}
