{
  "formatVersion": "1.1",
  "component": {
    "url": "../../runtime/1.5.0-SNAPSHOT/runtime-1.5.0-SNAPSHOT.module",
    "group": "com.squareup.sqldelight",
    "module": "runtime",
    "version": "1.5.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "xwktddyadzbtnf4duirkvykzdi"
    }
  },
  "variants": [
    {
      "name": "tvosArm64-api",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-common",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-collections",
          "version": {
            "requires": "1.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "runtime.klib",
          "url": "runtime-tvosarm64-1.5.0-SNAPSHOT.klib",
          "size": 41263,
          "sha512": "fd4da41a2dd68533af71c3ab7bfaa878cbeb060bb4cf8747e61e5a9da22ccf21c4bc6818a335cb88b7850a5105a1d24494a17ecd2e154cef99cacef4dbc0eb52",
          "sha256": "70b4928a376bba07e0f78704851c964096c2ad4150ac2fe6b28049be38da60c5",
          "sha1": "f8656ffd7bbb4a416293a06bba363672a5d0a477",
          "md5": "598d9571825267b1277a742cd7164955"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../runtime-metadata/1.5.0-SNAPSHOT/runtime-metadata-1.5.0-SNAPSHOT.module",
        "group": "com.squareup.sqldelight",
        "module": "runtime-metadata",
        "version": "1.5.0-SNAPSHOT"
      }
    }
  ]
}
